# get summary count of available timeslots by day
GET https://rich-gold-basket-clam-cape.cyclic.app/api/appointments
###

# get list of all time slots for a specific day
GET https://rich-gold-basket-clam-cape.cyclic.app/api/appointments/2023-01-28
###

# get list of all appointments for a user
GET https://rich-gold-basket-clam-cape.cyclic.app/api/appointments/booked/gs
###

# get list of all users
GET https://rich-gold-basket-clam-cape.cyclic.app/api/users/
###

# update availability for a specific appointment (switch between unavailable 0 and available 1)
PATCH  https://rich-gold-basket-clam-cape.cyclic.app/api/appointments/63bd329544e4da789091b5a0
Content-Type: application/json

{
    "username": "gs",
    "available": 0
}

###

# Test the stripe payment function
POST https://rich-gold-basket-clam-cape.cyclic.app/api/payment

###
